FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git curl unzip zip libpng-dev libonig-dev \
    libxml2-dev libzip-dev libicu-dev default-mysql-client \
    && docker-php-ext-install \
    pdo pdo_mysql mbstring exif pcntl bcmath gd zip intl opcache \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/backend

CMD ["php-fpm"]